apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "/bin/sh", "-c", "env; while true; do sleep 3600; done"]
      env:
        - name: USERNAME
          valueFrom: 
            configMapKeyRef:
              name: test-cm
              key: user
        - name: INPUT_JSON
          valueFrom:
            configMapKeyRef:
              name: test-cm
              key: all.json
      envFrom:
        - configMapRef:
            name: fromenv-map
        - configMapRef:
            name: test-cm

