apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: "nfs-class"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs-share
    server: 192.168.1.222
  persistentVolumeReclaimPolicy: Delete
