apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env; while true; do sleep 3600; done" ]
      volumeMounts:
        - name: secret-vol
          mountPath: /credentials
      env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-pass
              key: mariadb-pass
  volumes:
    - name: secret-vol
      secret:
        secretName: my-secret
