apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: ""  # Pusta storageClassName musi być wyraźnie ustawiona, w przeciwnym razie zostanie ustawiona domyślna 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
