apiVersion: v1
kind: Pod
metadata:
  labels:
    kubernetes.io/app: web
  name: test-dns
spec:
  containers:
    - image: 'radial/busyboxplus:curl'
      name: busybox
      command: [ 'sh', '-c', 'while true; do sleep 3600; done' ]
