apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  labels:
    app: init
spec: 
  initContainers:
  - name: delay
    image: busybox
    command: ['sleep', '30']
  - name: prepare
    image: busybox
    command: ['sh', '-c', 'echo mywebsite > /output/index.html']
    volumeMounts:
    - name: sharedvol
      mountPath: /output
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: sharedvol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: sharedvol
    emptyDir: {} 

