apiVersion: v1
kind: Pod
metadata:
  name: nodeselector2-pod
spec:
  nodeSelector:
    kubernetes.io/app: web
  containers:
  - image: nginx
    name: c1
    ports:
    - containerPort: 80
      protocol: TCP
