apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
#    podAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#      - labelSelector:
#          matchExpressions:
#          - key: kubenretes.io/zone 
#            operator: In
#            values:
#            - europe
#        topologyKey: kubernetes.io/country
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: kubenretes.io/zone
              operator: In
              values:
              - europe
          topologyKey: kubernetes.io/country 
  containers:
  - name: with-pod-affinity
    image: registry.k8s.io/pause:2.0
